version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"  # Проброс порта на локальный хост
    volumes:
      - .:/app  # Монтируем локальную директорию в контейнер
    environment:
      - ENV=development  # Можно добавить переменные окружения по необходимости
