version: "3.8"

services:
  web:
    build: .
    command: hypercorn --reload -b 0.0.0.0:5000 app:asgi_app
    restart: always
    networks:
      - syphon_network
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      QUART_APP: "app:asgi_app"
      QUART_ENV: "development"
networks:
  syphon_network:
    external: true
